
  version: '3'

  services:
    db:
      image: postgres:12.0
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env

    web:
      build: .
      command: gunicorn dockerIntern.wsgi:application --bind 0.0.0.0:$PORT
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db

  volumes:
    postgres_data: